language: node_js
node_js:
  - "13"
script:
  - yarn lint
  - yarn build
before_deploy:
  - yarn postbuild
cache: yarn
deploy:
  edge: true
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: dist
  name: Dominik Moritz
  email: domoritz@gmail.com
  project-name: editor
  on:
    branch: master
    tags: true
addons:
  apt:
    packages:
      - parallel
